/n'\" t
.TH "YAY" "8" "2018-02-29" "Yay v3\&.411+" "Yay Manual"
.nh
.ad l
.SH "NAME"
yay \- AUR Helper written in go
.SH "SYNOPSIS"
.sp
\fIyay\fR <operation> [options] [targets]
.sp
\fIyay\fR <search pattern>
.SH "DESCRIPTION"
.sp
Yay is a Pacman wrapper with AUR support\&. It passes options to Makepkg and
Pacman after resolving packages to install/upgrade\&.
.sp
This manpage only covers options unique to Yay\&. For other options see
\fBpacman(8)\fR\&.
.SH "YAY OPERATIONS"
.PP
\fB\-Y, --yay\fR
.RS 4
Perform yay specific operations\&. This is the default if no other operation is
selected\&.
.RE
.PP
\fB\-P, --print\fR
.RS 4
Perform yay specific print operations\&.
.RE
.PP
\fB\-G, --getpkgbuild\fR
.RS 4
Downloads PKGBUILD from ABS or AUR\&.
.RE
.PP
If no operation is selected -Y will be assumed\&.
.SH "EXTENDED PACMAN OPERATIONS"
.PP
\fB\-S, -Si, -Ss, -Su\fR
.RS 4
These operations are extended to support both AUR and repo packages\&.
.RE
.PP
\fB\-R\fR
.RS 4
Yay will also remove cached data about devel packages\&.
.RE
.SH "YAY OPTIONS (APPLY TO -Y AND --YAY)"
.PP
\fB<NO OPTION>\fR
.RS 4
Displays a list of packages matching the search terms and prompts the user on
which packages to install (yogurt mode)\&.
.RE
.PP
\fB   \-\-gendb\fR
.RS 4
Generate development package databse\&. Tracks the latest commit for each
development package, when there is a new commit Yay will know to update\&. This
is done per package whenever a package is synced. This option should only be
used when migrating to Yay from another AUR helper.
.RE
.PP
\fB\-c \-\-clean\fR
.RS 4
Remove unneeded dependencies\&.
.RE
.SH "PRINT OPTIONS (APPLY TO -P AND --PRINT)"
\fB\-c \-\-complete\fR
.RS 4
Print a list of all AUR and repo packages\&. This is to allow shell completion
and is not intended to be used directly by the user\&.
.RE
.PP
\fB\-f \-\-fish\fR
.RS 4
During complete adjust the output for the fish shell\&.
.RE
.PP
\fB\-d \-\-defaultconfig\fR
.RS 4
Print default yay configuration\&.
.RE
.PP
\fB\-g \-\-config\fR
.RS 4
Print current yay configuration\&.
.RE
.PP
\fB\-n \-\-numberupgrades\fR
.RS 4
Print number of packages that need to be updated\&. Note this does not preform
a database refresh\&. Run \fByay -Sy\fR Before this for an up to date result\&.
.RE
.PP
\fB\-s \-\-stats\fR
.RS 4
Displays information about installed packages and system health\&. If there are
orphaned, out-of-date or packages that no longer exist on the AUR warnings will
be displayed\&.
.RE
.PP
\fB\-u \-\-upgrades\fR
.RS 4
Print Names of packages that need to be updated\&. Note this does not preform
a database refresh\&. Run \fByay -Sy\fR Before this for an up to date result\&.
.PP
.SH "PERMANENT CONFIGURATION SETTINGS"
.PP
These options will be saved to disk and reapplied next time Yay is ran\&.
.PP
\fB\-\-topdown\fR
.RS 4
Display repository packages first and then AUR packages\&.
.RE
.PP
\fB\-\-bottomup\fR
.RS 4
Show AUR packages first and then repository packages\&.
.RE
.PP
\fB\-\-devel\fR
.RS 4
During sysupgrade also check AUR development packages for updates\&. Currently
only GitHub packages are supported\&.
.RE
.PP
\fB\-\-nodevel\fR
.RS 4
Do not check for development packages updates during sysupgrade\&.
.RE
.PP
\fB\-\-afterclean\fR
.RS 4
Remove package sources after successful Install\&.
.RE
.PP
\fB\-\-noafterclean\fR
.RS 4
Do not remove package sources after successful Install\&.
.RE
.PP
\fB\-\-timeupdate\fR
.RS 4
During sysupgrade also compare the build time of installed packages against
the last modification time of each package's AUR page\&.
.RE
.PP
\fB\-\-notimeupdate\fR
.RS 4
Do not consider build times during sysupgrade\&.
.RE
.PP
\fB\-\-redownload\fR
.RS 4
When downloading pkgbuilds if the pkgbuild is found in cache and is equal or
newer than the AUR's version use that instead of downloading a new one\&.
.RE
.PP
\fB\-\-noredownload\fR
.RS 4
Always download pkgbuilds even when a copy is avaliable in cache\&.
.RE
.SH "EXAMPLES"
.PP
yay \fIfoo\fR
.RS 4
Search and install from the repos and the \fBAUR\fR\ using yogurt mode\&.
.RE
.PP
yay -Syu
.RS 4
Update package list and upgrade all currently installed repo and \fBAUR\fR\&.
.RE
.PP
yay -S \fIfoo\fR
.RS 4
Installs package \fIfoo\fR from the repos or the \fBAUR\fR\&.
.RE
.PP
yay -Ss \fIfoo\fR
.RS 4
Searches for package \fIfoo\fR on the repos or the \fBAUR\fR\&.
.RE
.PP
yay -Si \fIfoo\fR
.RS 4
Gets information about package \fIfoo\fR from the repos or the \fBAUR\fR\&.
.RE
.PP
yay -S \fIfoo\fR
.RS 4
Installs package \fIfoo\fR from the repos or the \fBAUR\fR\&.
.RE
.PP
yay --stats
.RS 4
Shows statistics for installed packages and system health\&.
.RE
.SH "SEE ALSO"
.sp
\fBmakepkg\fR(8)
\fBpacman\fR(8)
\fBpacman\&.conf\fR(5)
.PP
See the arch wiki at https://wiki\&.archlinux\&.org/index\&.php/Arch_User_Repository for more info on the \fBAUR\fR\&.
.SH "BUGS"
.PP
Please report bugs to our GitHub page https://github\&.com/Jguer/yay
.SH "AUTHORS"
.sp
Jguer <joaogg3@gmail\&.com>
.br
Morgana <morganamilo@gmail\&.com>
