# /etc/yay.conf - System-wide yay configuration
[options]

# AUR Settings
AurUrl = https://aur.archlinux.org
#AurRpcUrl = https://aur.archlinux.org/rpc

# Directories
BuildDir = ~/.cache/yay

# Binaries
#Editor = vim
#EditorFlags = 
MakepkgBin = makepkg
#MakepkgConf = 
PacmanBin = pacman
PacmanConf = /etc/pacman.conf
GitBin = git
GpgBin = gpg
SudoBin = sudo

# Flags
# GpgFlags = 
# MFlags = 
# GitFlags = 
# SudoFlags = 

# Search/Display
BottomUp
# SingleLineResults
SeparateSources

# Sorting
#SortBy = 
SearchBy = name-desc

# Build options
#Devel
#CleanAfter
#KeepSrc
#BatchInstall

RemoveMake = ask

# Download options
ReDownload = no
ReBuild = no
PgpFetch

# Menus
CleanMenu
DiffMenu
# EditMenu

# Prompts
#AnswerClean = 
#AnswerDiff = 
#AnswerEdit = 
#AnswerUpgrade = 

# Behavior
CombinedUpgrade
#SudoLoop
#Provides
#UseAsk
DoubleConfirm
Rpc
#Debug

# Limits
RequestSplitN = 150
CompletionInterval = 7
MaxConcurrentDownloads = 1
