'\" t
.TH "YAY" "8" "2018-02-29" "Yay v3\&.460+" "Yay Manual"
.nh
.ad l
.SH "NAME"
yay \- AUR Helper written in go
.SH "SYNOPSIS"
.sp
\fIyay\fR <operation> [options] [targets]
.sp
\fIyay\fR <search pattern>
.sp
\fIyay\fR
.SH "DESCRIPTION"
.sp
Yay is a Pacman wrapper with AUR support\&. It passes options to Makepkg and
Pacman after resolving packages to install/upgrade\&.
.sp
This manpage only covers options unique to Yay\&. For other options see
\fBpacman(8)\fR\&.
.SH "YAY OPERATIONS"
.PP
\fB\-Y, --yay\fR
.RS 4
Perform yay specific operations\&. This is the default if no other operation is
selected\&.
.RE
.PP
\fB\-P, --print\fR
.RS 4
Perform yay specific print operations\&.
.RE
.PP
\fB\-G, --getpkgbuild\fR
.RS 4
Downloads PKGBUILD from ABS or AUR\&.
.RE
.PP
If no arguments are provided 'yay -Syu' will be performed\&.
.RE
.PP
If no operation is selected -Y will be assumed\&.
.SH "EXTENDED PACMAN OPERATIONS"
.PP
\fB\-S, -Si, -Ss, -Su, -Sc, -Qu\fR
.RS 4
These operations are extended to support both AUR and repo packages\&.
.RE
.PP
\fB\-Sc\fR
.RS 4
Yay will also clean cached AUR package and any untracked Files in the
cache\&. Untracked files cleaning only works for packages downloaded
using gitclone\&. Cleaning untracked files will wipe any downloaded
sources or built packages but will keep already downloaded vcs sources\&.
.RE
.PP
\fB\-R\fR
.RS 4
Yay will also remove cached data about devel packages\&.

.RE
.SH "YAY OPTIONS (APPLY TO -Y AND --YAY)"
.PP
\fB<NO OPTION>\fR
.RS 4
Displays a list of packages matching the search terms and prompts the user on
which packages to install (yogurt mode)\&.
.RE
.PP
\fB   \-\-gendb\fR
.RS 4
Generate development package database\&. Tracks the latest commit for each
development package, when there is a new commit Yay will know to update\&. This
is done per package whenever a package is synced. This option should only be
used when migrating to Yay from another AUR helper.
.RE
.PP
\fB\-c \-\-clean\fR
.RS 4
Remove unneeded dependencies\&.
.RE
.SH "PRINT OPTIONS (APPLY TO -P AND --PRINT)"
\fB\-c \-\-complete\fR
.RS 4
Print a list of all AUR and repo packages\&. This is to allow shell completion
and is not intended to be used directly by the user\&.
.RE
.PP
\fB\-f \-\-fish\fR
.RS 4
During complete adjust the output for the fish shell\&.
.RE
.PP
\fB\-d \-\-defaultconfig\fR
.RS 4
Print default yay configuration\&.
.RE
.PP
\fB\-g \-\-config\fR
.RS 4
Print current yay configuration\&.
.RE
.PP
\fB\-n \-\-numberupgrades\fR
.RS 4
Print number of packages that need to be updated\&. Note this does not perform
a database refresh\&. Run \fByay -Sy\fR Before this for an up to date result\&.
.RE
.PP
\fB\-s \-\-stats\fR
.RS 4
Displays information about installed packages and system health\&. If there are
orphaned, out-of-date or packages that no longer exist on the AUR warnings will
be displayed\&.
.RE
.PP
\fB\-u \-\-upgrades\fR
.RS 4
Print Names of packages that need to be updated\&. Note this does not perform
a database refresh\&. Run \fByay -Sy\fR Before this for an up to date result\&.
.PP
.SH "PERMANENT CONFIGURATION SETTINGS"
.PP
\fB\-\-save\fR
.RS 4
Causes the following options to be saved back to the config file\&. This
provides an easy way to change config options without directly editing the
file\&.
.RE
.PP
\fB\-\-builddir <dir>\fR
.RS 4
Directory to use for Building AUR Packages\&. This directory is also used as
the AUR cache when deciding if Yay should should skip builds\&.
.RE
.PP
\fB\-\-editor <file>\fR
.RS 4
Editor to use when editing PKGBUILDs\&. If this is not set the \fBEDITOR\fR
environment variable will be checked, followed by \fBVISUAL\fR\&. If none of
these are set Yay will prompt the user for an editor\&.
.RE
.PP
\fB\-\-editorflags <flags>\fR
.RS 4
Passes arguments to the editor\&. These flags get passed to every instance where
the editor is called by Yay. Arguments are split on whitespace before being
passed to gpg. Multiple arguments may be passed by supplying a space
separated list that is quoted by the shell.
.RE
.PP
\fB\-\-makepkg <file>\fR
.RS 4
The command to use for \fBmakepkg\fR calls. This can be a command in
\fBPATH\fR or an absolute path to the file\&.
.RE
.PP
\fB\-\-pacman <file>\fR
.RS 4
The command to use for \fBpacman\fR calls. This can be a command in
\fBPATH\fR or an absolute path to the file\&.
.RE
.PP
\fB\-\-tar <file>\fR
.RS 4
The command to use for \fBbsdtar\fR calls. This can be a command in
\fBPATH\fR or an absolute path to the file\&.
.RE
.PP
\fB\-\-git <file>\fR
.RS 4
The command to use for \fBgit\fR calls. This can be a command in
\fBPATH\fR or an absolute path to the file\&.
.RE
.PP
\fB\-\-gpg <file>\fR
.RS 4
The command to use for \fBgpg\fR calls. This can be a command in
\fBPATH\fR or an absolute path to the file\&.
.RE
.PP
\fB\-\-config <file>\fR
.RS 4
The pacman config file to use\&.
.RE
.PP
\fB\-\-requestsplitn <n>\fR
.RS 4
The maximum amount of packages to request per AUR query\&. The higher the
number the faster AUR requests will be\&. Requesting too many packages in one
AUR query will cause an error\&. This should only make a noticeable difference
with very large requests (>500) packages\&.
.RE
.PP
\fB\-\-sortby <votes|popularity|id|baseid|name|base|submitted|modified>\fR
.RS 4
Sort AUR results by a specific field during search\&.
.RE
.PP
\fB\-\-answerclean <All|None|Installed|NotInstalled|...>\fR
.RS 4
Set a predetermined answer for the clean build menu question\&. This answer
will be used instead of reading from standard input but will be treated exactly
the same when parsed\&.
.RE
.PP
\fB\-\-answeredit <All|None|Installed|NotInstalled|...>\fR
.RS 4
Set a predetermined answer for the edit pkgbuild menu question\&. This answer
will be used instead of reading from standard input but will be treated exactly
the same when parsed\&.
.RE
.PP
\fB\-\-answerupgrade\fR <Repo|^Repo|None|...>
.RS 4
Set a predetermined answer for the upgrade menu question\&. Selects which packages
groups or repos to omit for updades\&. This answer will be used instead of
reading from standard input but will be treated exactly the same\&.
.RE
.PP
\fB\-\-noanswerclean\fR
.RS 4
Unset the answer for the clean build menu\&.
.RE
.PP
\fB\-\-noansweredit\fR
.RS 4
Unset the answer for the edit pkgbuild menu\&.
.RE
.PP
\fB\-\-noanswerupgrade\fR
.RS 4
Unset the answer for the upgrade menu\&.
.RE
.PP
\fB\-\-topdown\fR
.RS 4
Display repository packages first and then AUR packages\&.
.RE
.PP
\fB\-\-bottomup\fR
.RS 4
Show AUR packages first and then repository packages\&.
.RE
.PP
\fB\-\-devel\fR
.RS 4
During sysupgrade also check AUR development packages for updates\&. Currently
only GitHub packages are supported\&.
.RE
.PP
\fB\-\-nodevel\fR
.RS 4
Do not check for development packages updates during sysupgrade\&.
.RE
.PP
\fB\-\-gitclone\fR
.RS 4
Use git to download and update PKGBUILDs\&. PKGBUILDs previously downloaded
using tarball will continue to use tarballs until the package is clean built\&.
Similarly, PKGBUILDs managed with git will continue to use git until the package
is clean built.\&.
.RE
.PP
\fB\-\-nogitclone\fR
.RS 4
Download and update PKGBUILDs using tarballs\&. The above conditions about
previously installed packages still apply\&.
.RE
.PP
\fB\-\-afterclean\fR
.RS 4
Remove package sources after successful Install\&.
.RE
.PP
\fB\-\-noafterclean\fR
.RS 4
Do not remove package sources after successful Install\&.
.RE
.PP
\fB\-\-timeupdate\fR
.RS 4
During sysupgrade also compare the build time of installed packages against
the last modification time of each package's AUR page\&.
.RE
.PP
\fB\-\-notimeupdate\fR
.RS 4
Do not consider build times during sysupgrade\&.
.RE
.PP
\fB\-\-redownload\fR
.RS 4
Always download pkgbuilds of targets even when a copy is available in cache\&.
.RE
.PP
\fB\-\-redownloadall\fR
.RS 4
Always download pkgbuilds of all AUR packages even when a copy is available
in cache\&.
.RE
.PP
\fB\-\-noredownload\fR
.RS 4
When downloading pkgbuilds if the pkgbuild is found in cache and is equal or
newer than the AUR's version use that instead of downloading a new one\&.
.RE
.PP
\fB\-\-rebuild\fR
.RS 4
Always build target packages even when a copy is available in cache\&.
.RE
.PP
\fB\-\-rebuildall\fR
.RS 4
Always build all AUR packages even when a copy is available
in cache\&.
.RE
.PP
\fB\-\-rebuildtree\fR
.RS 4
When installing an AUR package rebuild and reinstall all of its AUR
dependencies recursivley, even the ones already installed. This flag allows
you to easily rebuild packages against your current system's libraries if they
have become incompatible.
.RE
.PP
\fB\-\-norebuild\fR
.RS 4
When building packages if the package is found in cache and is an equal version
to the one wanted skip the package build and use the existing package\&.
.RE
.PP
\fB\-\-mflags <flags>\fR
.RS 4
Passes arguments to makepkg\&. These flags get passed to every instance where
makepkg is called by Yay. Arguments are split on whitespace before being
passed to makepkg. Multiple arguments may be passed by supplying a space
separated list that is quoted by the shell.
.RE
.PP
\fB\-\-gpgflags <flags>\fR
.RS 4
Passes arguments to gpg\&. These flags get passed to every instance where
gpg is called by Yay. Arguments are split on whitespace before being
passed to gpg. Multiple arguments may be passed by supplying a space
separated list that is quoted by the shell.
.RE
.PP
\fB\-\-sudoloop\fR
.RS 4
Loop sudo calls in the background to prevent sudo from timing out during long
builds\&.
.RE
.PP
\fB\-\-nosudoloop\fR
.RS 4
Do not loop sudo calls in the background\&.
.RE
.SH "EXAMPLES"
.PP
yay \fIfoo\fR
.RS 4
Search and install from the repos and the \fBAUR\fR\ using yogurt mode\&.
.RE
.PP
yay -Syu
.RS 4
Update package list and upgrade all currently installed repo and \fBAUR\fR\&.
.RE
.PP
yay -S \fIfoo\fR
.RS 4
Installs package \fIfoo\fR from the repos or the \fBAUR\fR\&.
.RE
.PP
yay -Ss \fIfoo\fR
.RS 4
Searches for package \fIfoo\fR on the repos or the \fBAUR\fR\&.
.RE
.PP
yay -Si \fIfoo\fR
.RS 4
Gets information about package \fIfoo\fR from the repos or the \fBAUR\fR\&.
.RE
.PP
yay -S \fIfoo\fR --mflags "--skipchecksums --skippgpcheck"
.RS 4
Installs \fIfoo\fR while skipping checksums and pgp checks\&.
.RE
.PP
yay --devel --save
.RS 4
Sets devel to true in the config\&.
.RE
.PP
yay -P --stats
.RS 4
Shows statistics for installed packages and system health\&.
.RE
.SH "FILES"
.sp
\fBCONFIG DIRECTORY\fR
.RS 4
The config directory is \fI$XDG_CONFIG_HOME/yay/\fR\&. if
\fB$XDG_CONFIG_HOME\fR is unset, the config directory will fall back to
\fI$HOME/.config/yay\fR\&.
.PP
\fIconfig.json\fR\& Is used to store all of Yay's config options\&. Editing
this file should be done through Yay, using the options
mentioned in \fBPERMANENT CONFIGURATION SETTINGS\fR\&.
.RE
.PP
\fBCACHE DIRECTORY\fR
.RS 4
The cache directory is \fI$XDG_CACHE_HOME/yay/\fR\&. if
\fB$XDG_CACHE_HOME\fR is unset, the cache directory will fall back to
\fI$HOME/.cache/yay\fR\&.
.PP
\fIaur_<shellname>\fR holds a list of of all packages, including the AUR,
for shell completion\&. The completion files are refreshed every 48 hours\&.
.PP
\fIvcs.json\fR tracks VCS packages and the latest commit of each source. If
any of these commits change the package will be upgraded during a devel update.
.RE
.PP
\fBBUILD DIRECTORY\fR
.RS 4
Unless otherwise set this should be the same as \fBCACHE DIRECTORY\fR. This
directory is used to store downloaded AUR Packages as well as any source files
and built packages from those packages\&.
.RE
.PP
\fBPACMAN.CONF\fR
.RS 4
Yay uses Pacman's config file to set certain pacman options either through
go-alpm or Yay itself. Options inherited include most libalpm options and
pacman options\&.
.PP
Notably \fBDatabases\fR, \fBColor\fR and \fB*Path/*Dir\fR options are used\&.
.RE
.PP
.SH "SEE ALSO"
.sp
\fBmakepkg\fR(8)
\fBPKGBUILD\fR(5)
\fBpacman\fR(8)
\fBpacman\&.conf\fR(5)
.PP
See the arch wiki at https://wiki\&.archlinux\&.org/index\&.php/Arch_User_Repository for more info on the \fBAUR\fR\&.
.SH "BUGS"
.PP
Please report bugs to our GitHub page https://github\&.com/Jguer/yay
.SH "AUTHORS"
.sp
Jguer <joaogg3@gmail\&.com>
.br
Morgana <morganamilo@gmail\&.com>
