name: Test against pacman-git
on:
  pull_request:
    paths-ignore:
      - "doc/**"
      - "**/*.po"
      - "README.md"
      - ".gitignore"

jobs:
  build:
    name: Lint and test yay (-git)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jguer/yay-builder:latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: checkout pacman-git
        run: |
          rm -rf pacman-git
          git clone --depth=1 https://aur.archlinux.org/pacman-git
          useradd github
          echo 'github ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          chmod -R 777 pacman-git
          su github -c 'cd pacman-git; yes | makepkg -si --nocheck'
      - name: Run Build and Tests with pacman-git
        run: |
          make test
