name: Test against pacman-git
on:
  pull_request:
    paths-ignore:
      - "doc/**"
      - "**/*.po"
      - "README.md"
      - ".gitignore"

jobs:
  build:
    name: Lint and test yay (-git)
    runs-on: ubuntu-latest
    container:
      image: jguer/yay-builder:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/cache@v3
        with:
          path: /home/runner/work/yay/yay/pacman-git
          key: ${{ runner.os }}-pacman-${{ hashFiles('/home/runner/work/yay/yay/pacman-git/PKGBUILD') }}
          restore-keys: |
            ${{ runner.os }}-pacman-
      - name: checkout pacman-git
        run: |
          git -C ./pacman-git pull || git clone https://aur.archlinux.org/pacman-git
          useradd github
          echo 'github ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          chmod -R 777 pacman-git
          su github -c 'cd pacman-git; yes | makepkg -i --nocheck'
      - name: Run Build and Tests with pacman-git
        run: |
          make test
